### ISSUE TITLE
Ability to add "Power Connection" items in the graphical view

### ISSUE THREAD

**Issue by danama** [Molkobain/itop-datacenter-view#6]
We have a rackable APC UPS that we would like to inject in the graphical view. 

Is this functionality can be implemented ?

**Comment by Molkobain** [comment]
Hi @danama,

How did you created the UPS, through a custom class or as a PowerSource? In the case of a custom class, what's its parent class?

**Comment by Molkobain** [comment]
Either way, the class won't have all the necessary attributes to be rendered in the rack, it needs at least:
- A link to rack (*rack_id* attribute)
- Its vertical position in the rack (*position_v* attribute)
- Optionally, its height (*nb_u* attribute), default is 1U

I can add an option to the extension so that you can specify in iTop configuration file which extras classes to display in the graphical view, but you will still need to alter the standard datamodel to add the missing attributes (can be done through your own extension). Are you familiar with making extension for iTop?

**Comment by Molkobain** [comment]
Looking into this, I think that the extension could natively modify the PDU class to:
- Add the _position_v_ attribute as it is already linked to a rack through _rack_id_
- Add the _nb_u_ attribute with a default value of 1U

iTop admins should not have to create an extension just to enable the PDU in the graphical view. :)

**Comment by Molkobain** [comment]
Thanks to your feedback, PDU are now natively available for racks and enclosures (I added the 2 attributes mentioned above). It will be part of the v1.4.0.

Regarding the paid version, I developed a new option enabling anyone to uses its custom classes (not derivated from DatacenterDevice) in racks and enclosures. They just need to have the required attributes (mentioned above)

Hope it will fit your needs 😊
